[2024-10-10 12:55:41,570: INFO: main: Welcome]
[2024-10-10 13:04:52,883: INFO: main: Welcome]
[2024-10-10 22:06:15,469: INFO: main: >>>>>> stage Main Pipeline started <<<<<<]
[2024-10-10 22:06:15,470: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\config\config.yaml loaded successfully]
[2024-10-10 22:06:15,471: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\params.yaml loaded successfully]
[2024-10-10 22:06:15,471: INFO: common: created directory at: artifacts]
[2024-10-10 22:06:15,473: INFO: common: created directory at: C:\dev\ml\projects\MLOPS_Project\artifacts\data_ingestion]
[2024-10-10 22:06:15,473: INFO: data_ingestion: Downloading TRAIN DATASET from: http://saliencydetection.net/duts/download/DUTS-TR.zip]
[2024-10-11 00:41:51,034: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\config\config.yaml loaded successfully]
[2024-10-11 00:41:51,037: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\params.yaml loaded successfully]
[2024-10-11 00:41:51,037: INFO: common: created directory at: artifacts]
[2024-10-11 00:41:51,038: INFO: common: created directory at: C:\dev\ml\projects\MLOPS_Project\artifacts\data_ingestion]
[2024-10-11 01:02:47,249: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-10-11 01:02:47,251: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\config\config.yaml loaded successfully]
[2024-10-11 01:02:47,253: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\params.yaml loaded successfully]
[2024-10-11 01:02:47,254: INFO: common: created directory at: artifacts]
[2024-10-11 01:02:47,254: ERROR: main: 'ConfigurationManager' object has no attribute 'get_model_trainer_config']
Traceback (most recent call last):
  File "c:\dev\ml\projects\MLOPS_Project\main.py", line 25, in <module>
    model_trainer.main()
  File "C:\dev\ml\projects\MLOPS_Project\src\clearbg\pipeline\stage_02_model_trainer.py", line 13, in main
    model_trainer_config = config.get_model_trainer_config()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_model_trainer_config'
[2024-10-11 01:03:20,502: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-10-11 01:03:20,503: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\config\config.yaml loaded successfully]
[2024-10-11 01:03:20,506: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\params.yaml loaded successfully]
[2024-10-11 01:03:20,506: INFO: common: created directory at: artifacts]
[2024-10-11 01:03:20,507: ERROR: main: 'TrainingConfig' object has no attribute 'get_data_ingestion_config']
Traceback (most recent call last):
  File "c:\dev\ml\projects\MLOPS_Project\main.py", line 25, in <module>
    model_trainer.main()
  File "C:\dev\ml\projects\MLOPS_Project\src\clearbg\pipeline\stage_02_model_trainer.py", line 14, in main
    trainer = Training(model_trainer_config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\ml\projects\MLOPS_Project\src\clearbg\components\model_trainer.py", line 20, in __init__
    self.data_ingestion_config = self.config_manager.get_data_ingestion_config()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TrainingConfig' object has no attribute 'get_data_ingestion_config'
[2024-10-11 01:06:48,073: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-10-11 01:06:48,074: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\config\config.yaml loaded successfully]
[2024-10-11 01:06:48,076: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\params.yaml loaded successfully]
[2024-10-11 01:06:48,076: INFO: common: created directory at: artifacts]
[2024-10-11 01:06:48,083: INFO: common: created directory at: C:\dev\ml\projects\MLOPS_Project\artifacts\data_ingestion]
[2024-10-11 01:06:48,084: INFO: common: created directory at: C:\dev\ml\projects\MLOPS_Project\artifacts\data_ingestion]
[2024-10-11 01:06:48,085: INFO: common: created directory at: C:\dev\ml\projects\MLOPS_Project\artifacts\training\saved_models\u2net]
[2024-10-11 01:06:52,519: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-10-11 01:06:52,522: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\config\config.yaml loaded successfully]
[2024-10-11 01:06:52,522: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\params.yaml loaded successfully]
[2024-10-11 01:06:52,523: INFO: common: created directory at: artifacts]
[2024-10-11 01:06:52,524: INFO: common: created directory at: C:\dev\ml\projects\MLOPS_Project\artifacts\data_ingestion]
[2024-10-11 01:06:52,524: INFO: common: created directory at: C:\dev\ml\projects\MLOPS_Project\artifacts\data_ingestion]
[2024-10-11 01:06:52,525: INFO: common: created directory at: C:\dev\ml\projects\MLOPS_Project\artifacts\training\saved_models\u2net]
[2024-10-11 01:06:52,856: ERROR: main: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
        ]
Traceback (most recent call last):
  File "c:\dev\ml\projects\MLOPS_Project\main.py", line 25, in <module>
    model_trainer.main()
  File "C:\dev\ml\projects\MLOPS_Project\src\clearbg\pipeline\stage_02_model_trainer.py", line 16, in main
    trainer.train()
  File "C:\dev\ml\projects\MLOPS_Project\src\clearbg\components\model_trainer.py", line 102, in train
    for i, data in enumerate(salobj_dataloader):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aryan Wadhawan\AppData\Roaming\Python\Python312\site-packages\torch\utils\data\dataloader.py", line 440, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aryan Wadhawan\AppData\Roaming\Python\Python312\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aryan Wadhawan\AppData\Roaming\Python\Python312\site-packages\torch\utils\data\dataloader.py", line 1038, in __init__
    w.start()
  File "C:\Users\Aryan Wadhawan\.conda\envs\mlopsproj\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aryan Wadhawan\.conda\envs\mlopsproj\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aryan Wadhawan\.conda\envs\mlopsproj\Lib\multiprocessing\context.py", line 337, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aryan Wadhawan\.conda\envs\mlopsproj\Lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aryan Wadhawan\.conda\envs\mlopsproj\Lib\multiprocessing\spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Aryan Wadhawan\.conda\envs\mlopsproj\Lib\multiprocessing\spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
        
[2024-10-11 01:56:41,792: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\config\config.yaml loaded successfully]
[2024-10-11 01:56:41,809: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\params.yaml loaded successfully]
[2024-10-11 01:56:41,810: INFO: common: created directory at: artifacts]
[2024-10-11 01:57:08,569: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\config\config.yaml loaded successfully]
[2024-10-11 01:57:08,571: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\params.yaml loaded successfully]
[2024-10-11 01:57:08,572: INFO: common: created directory at: artifacts]
[2024-10-11 01:57:41,208: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\config\config.yaml loaded successfully]
[2024-10-11 01:57:41,210: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\params.yaml loaded successfully]
[2024-10-11 01:57:41,211: INFO: common: created directory at: artifacts]
[2024-10-11 01:59:02,174: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\config\config.yaml loaded successfully]
[2024-10-11 01:59:02,176: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\params.yaml loaded successfully]
[2024-10-11 01:59:02,177: INFO: common: created directory at: artifacts]
[2024-10-11 01:59:19,299: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\config\config.yaml loaded successfully]
[2024-10-11 01:59:19,301: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\params.yaml loaded successfully]
[2024-10-11 01:59:19,302: INFO: common: created directory at: artifacts]
[2024-10-11 01:59:51,904: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\config\config.yaml loaded successfully]
[2024-10-11 01:59:51,906: INFO: common: yaml file: C:\dev\ml\projects\MLOPS_Project\params.yaml loaded successfully]
[2024-10-11 01:59:51,907: INFO: common: created directory at: artifacts]
